[project]
name = "gold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "finnhub-python>=2.4.24",
    "requests>=2.32.5",
    "websocket>=0.2.1",
]
